---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: debug-statements
          - id: mixed-line-ending
          - id: requirements-txt-fixer
          - id: check-added-large-files
          - id: detect-private-key
          - id: pretty-format-json
            args: [--autofix]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.3
      hooks:
          - id: pyupgrade
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.12.12
      hooks:
          - id: ruff-check
            args: [--fix]
          - id: ruff-format
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/crate-ci/typos
      rev: v1.38.1
      hooks:
          - id: typos
